server:
  port: 9724

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true #使用服务发现路由（开启从注册中心动态创建路由的功能，利用微服务名进行路由)
      routes:
        - id: demo #设置路由id
          uri: http://www.baidu.com
          predicates:
            - After=2021-01-10T17:42:47.789-07:00
#springboot 默认的日志级别是info,改为debug
logging:
  level: #指定这个包下的日子为debug
    org.gjw.feign.*: debug
